version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ellty_app
    ports:
      - "${PORT:-3001}:3001"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3001}
      NODE_ENV: ${NODE_ENV:-production}
    networks:
      - ellty_network
    restart: always


networks:
  ellty_network:
    driver: bridge
